(function(){
  'use strict';
  var cfg=window.SAMEWAY_CONFIG||{},base=String(cfg.SUPABASE_URL||'').replace(/\/$/,''),anon=String(cfg.SUPABASE_ANON_KEY||'');
  var endpoint=base+'/functions/v1/subway-message';
  var sid=sessionStorage.getItem('sameway:ride-session')||('ride_'+Math.random().toString(36).slice(2)+Date.now().toString(36));sessionStorage.setItem('sameway:ride-session',sid);
  var nick=sessionStorage.getItem('sameway:ride-nick')||['졸린참새','출근한수달','커피찾는판다','퇴근바라기','달리는고양이'][Math.floor(Math.random()*5)];sessionStorage.setItem('sameway:ride-nick',nick);
  var seen=new Map(),lastIso='1970-01-01T00:00:00Z',timer=null,mounted=false;
  function headers(){return {'Content-Type':'application/json',apikey:anon,Authorization:'Bearer '+anon};}
  async function api(payload){var r=await fetch(endpoint,{method:'POST',headers:headers(),body:JSON.stringify(payload)});var j={};try{j=await r.json();}catch(_){}if(!r.ok)throw Object.assign(new Error(j.category||j.error||('HTTP '+r.status)),{status:r.status,data:j});return j;}
  function roomKey(){var l=window.SAMEWAY_LOCATION_STATE||{},a=window.SAMEWAY_ACCESS_STATE||{};return [l.line||a.line||'unknown',l.directionLabel||a.directionLabel||'unknown'].join('|');}
  function esc(s){return String(s||'').replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c;});}
  function draw(){var box=document.getElementById('sameway-fast-messages');if(!box)return;var arr=[].concat(Array.from(seen.values())).sort(function(a,b){return new Date(a.created_at)-new Date(b.created_at);});box.innerHTML=arr.length?arr.map(function(m){return '<div class="sw-fast-msg '+(m.session_id===sid?'me':'')+'"><div class="n">'+(m.session_id===sid?'나':esc(m.nick))+'</div><div class="b">'+esc(m.body)+'</div></div>';}).join(''):'<div class="sw-fast-empty">같은 방향 사람에게 가볍게 한마디 남겨보세요.</div>';box.scrollTop=box.scrollHeight;}
  async function poll(){if(document.hidden)return;var room=roomKey();if(room.indexOf('unknown')>=0)return;try{var j=await api({action:'list',room_key:room,after:lastIso});(j.messages||[]).forEach(function(m){seen.set(m.id,m);if(m.created_at>lastIso)lastIso=m.created_at;});draw();}catch(_){} }
  async function send(text){var body=String(text||'').trim();if(!body)return;var temp='tmp_'+Date.now();var m={id:temp,room_key:roomKey(),session_id:sid,nick:nick,body:body,created_at:new Date().toISOString(),pending:true};seen.set(temp,m);draw();try{var j=await api({action:'send',room_key:m.room_key,session_id:sid,nick:nick,body:body});seen.delete(temp);if(j.message)seen.set(j.message.id,j.message);draw();return true;}catch(e){seen.delete(temp);draw();var warn=document.getElementById('sameway-fast-warning');if(warn){warn.textContent=e&&e.data&&e.data.blocked?'보낼 수 없는 표현이 포함되어 있어요.':'메시지를 보내지 못했어요.';setTimeout(function(){warn.textContent='';},2600);}return false;}}
  async function leave(){try{await api({action:'leave',session_id:sid});}catch(_){}seen.clear();lastIso='1970-01-01T00:00:00Z';draw();sessionStorage.removeItem('sameway:ride-session');sessionStorage.removeItem('sameway:ride-nick');}
  function mount(){
    var feed=document.querySelector('.feed'),comp=document.querySelector('.comp');if(!feed||!comp)return;
    var legacyMsgs=feed.querySelector('.msgs');if(legacyMsgs)legacyMsgs.style.display='none';var legacyIpt=comp.querySelector('.ipt');if(legacyIpt)legacyIpt.style.display='none';var nk=comp.querySelector('.nk');if(nk)nk.style.display='none';
    if(!document.getElementById('sameway-fast-chat')){var wrap=document.createElement('div');wrap.id='sameway-fast-chat';wrap.innerHTML='<div id="sameway-fast-messages"></div>';if(legacyMsgs)legacyMsgs.parentNode.insertBefore(wrap,legacyMsgs);else feed.appendChild(wrap);}
    if(!document.getElementById('sameway-fast-composer')){var c=document.createElement('div');c.id='sameway-fast-composer';c.innerHTML='<div id="sameway-fast-warning"></div><div class="sw-fast-row"><textarea maxlength="300" rows="1" placeholder="가볍게 한마디"></textarea><button>↑</button></div><div class="sw-fast-note">'+esc(nick)+' · 내리면 이 대화와 이름이 사라져요</div>';comp.appendChild(c);var ta=c.querySelector('textarea'),btn=c.querySelector('button');var go=async function(){var v=ta.value;ta.value='';await send(v);};btn.onclick=go;ta.addEventListener('keydown',function(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();go();}});}
    if(!mounted){mounted=true;timer=setInterval(poll,650);poll();}
  }
  document.addEventListener('click',function(e){var t=e.target;if(t&&t.closest&&t.closest('.getoff'))leave();},true);
  window.addEventListener('subway:access',function(e){if(e.detail&&e.detail.status==='blocked'&&mounted)leave();});
  document.addEventListener('visibilitychange',function(){if(!document.hidden)poll();});
  new MutationObserver(mount).observe(document.documentElement,{childList:true,subtree:true});mount();
  var style=document.createElement('style');style.textContent='#sameway-fast-chat{display:flex;flex-direction:column;gap:8px}#sameway-fast-messages{display:flex;flex-direction:column;gap:8px;max-height:310px;overflow:auto}.sw-fast-msg{max-width:82%;background:#fff;border:1px solid #E1E5EB;border-radius:15px;padding:10px 12px;box-shadow:0 2px 8px rgba(20,30,48,.05)}.sw-fast-msg.me{align-self:flex-end;background:#E7FAF5;border-color:#CFF3EB}.sw-fast-msg .n{font-size:10.5px;color:#727A86;font-weight:800;margin-bottom:3px}.sw-fast-msg .b{font-size:14px;line-height:1.45}.sw-fast-empty{text-align:center;color:#A4ABB6;font-size:12px;padding:18px}#sameway-fast-composer{padding:0 12px 10px}.sw-fast-row{display:flex;gap:8px}.sw-fast-row textarea{flex:1;border:1px solid #E1E5EB;border-radius:14px;padding:11px 12px;resize:none;font:inherit;outline:none}.sw-fast-row button{width:44px;border:0;border-radius:14px;background:#16C7A6;color:#fff;font-size:18px;font-weight:900}.sw-fast-note{font-size:10.5px;color:#A4ABB6;margin-top:5px}.sw-fast-warning{font-size:11px;color:#E5484D}#sameway-fast-warning{font-size:11px;color:#E5484D;margin-bottom:4px}';document.head.appendChild(style);
  window.SAMEWAY_INSTANT_CHAT={version:'4.0.0',send:send,leave:leave,poll:poll};
})();